"""add core entities

Revision ID: 85f1b45c01c8
Revises: 
Create Date: 2025-08-17 01:02:16.004561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f1b45c01c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('rate_per_hour', sa.Integer(), nullable=True),
    sa.Column('offline_ok', sa.Boolean(), nullable=True),
    sa.Column('availability_json', sa.JSON(), nullable=True),
    sa.Column('rating_avg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('budget_range', sa.String(), nullable=True),
    sa.Column('schedule_pref', sa.String(), nullable=True),
    sa.Column('mode_pref', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('keywords_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('experts')
    # ### end Alembic commands ###
